patient/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='list'),
    url(r'^new$', views.create, name='new'),
    url(r'^(?P<patient_id>[0-9]+)$', views.edit, name='edit'),
    url(r'^(?P<patient_id>[0-9]+)/print$', views.print_patient, name='print'),
    # url(r'^(?P<patient_id>[0-9]+)$', views.results, name='delete')
]

sdh/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import index
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', index),
    url(r'^admin/', admin.site.urls),
    url(r'^patients/', include('patient.urls', namespace='patient')),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'index.html'}, name='logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

patient/models.py
from django.db import models
from datetime import datetime


CHARACTER_CHOICES = ['ELETIVO', 'URGÊNCIA']
REFERAL_PLACES = ['Clínica da família', 'Policlínica Piquet Carneiro', 'Outro']

class Patient(models.Model):
    """Patient model"""
    name = models.CharField(max_length=100, verbose_name="Nome do paciente")
    mother_name = models.CharField(
        max_length=100, verbose_name="Nome da mãe", null=True, blank=True)
    address = models.CharField(max_length=300, verbose_name="Endereço")
    phone = models.CharField(max_length=100, verbose_name="Telefone")
    birthdate = models.DateField(verbose_name="Data de nascimento")
    exame_number = models.CharField(
        verbose_name="Número do exame laboratorial", max_length=40,
        null=True, blank=True)
    notes = models.CharField(
        max_length=300, verbose_name="Observações", null=True, blank=True)
    prostate_history = models.NullBooleanField(
        verbose_name="Tem alguém na família com problemas na próstata")
    trouble_urinating = models.NullBooleanField(
        verbose_name="Problemas para urinar?")
    suspicious_nodule = models.NullBooleanField(
        verbose_name="Possui nódulo suspeito?")

    psa_positive = models.NullBooleanField(
        verbose_name="Exame de PSA Positivo?",
        default=False, blank=True, null=True)

    has_referral = models.NullBooleanField(
        verbose_name="Encaminhamento", default=False)

    referral_character = models.CharField(
        max_length=100,
        verbose_name="Caráter",
        null=True,
        blank=True,
        choices=[(str(i), CHARACTER_CHOICES[i]) for i in range(len(CHARACTER_CHOICES))])

    referral_place = models.CharField(
        max_length=100,
        verbose_name="Local de encaminhamento",
        null=True,
        blank=True,
        choices=[(str(i), REFERAL_PLACES[i]) for i in range(len(REFERAL_PLACES))])

    other_referral_place = models.CharField(
        max_length=100, verbose_name="Especificar local",
        null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_age(self):
        today = datetime.now().date()
        age = today.year - self.birthdate.year
        if today.month < self.birthdate.month:
            age = age - 1
        elif today.month == self.birthdate.month and \
                today.day >= self.birthdate.day:
            age = age - 1
        return age


    class Meta:
        ordering = ['-created_at']

patient/forms.py
from django.forms import ModelForm, DateField
from .models import Patient
from django.core.validators import EMPTY_VALUES


class PatientForm(ModelForm):
    birthdate = DateField(input_formats=('%d/%m/%Y',))
    class Meta:
        model = Patient
        exclude = ('created_at',)

    def clean(self):
        has_referral = self.cleaned_data.get('has_referral', False)
        if has_referral:
            referral_character = self.cleaned_data.get(
                'referral_character', None)
            if referral_character in EMPTY_VALUES:
                self._errors['referral_character'] = self.error_class([
                    'Caráter do encaminhamento obrigatório'])
            referral_place = self.cleaned_data.get('referral_place', None)
            other_referral_place = self.cleaned_data.get(
                'other_referral_place', None)
            if referral_place in EMPTY_VALUES:
                self._errors['referral_place'] = self.error_class([
                        'Local do encaminhamento obrigatório'])
            elif int(referral_place) == 2 and \
                    other_referral_place in EMPTY_VALUES:
                self._errors['other_referral_place'] = self.error_class([
                    'Local do encaminhamento obrigatório'])
        print(self.cleaned_data.get('birthdate'))
        return self.cleaned_data

login/views.py
from django.shortcuts import render

patient/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Patient, CHARACTER_CHOICES, REFERAL_PLACES
from .forms import PatientForm
from datetime import datetime
from django.contrib.auth.decorators import login_required


def get_registry_number():
    return Patient.objects.count() + 1

def create_flash(color, message):
    return {
        'color': color,
        'message': message
    }

def get_error_msg(form):
    return 'Formulário inválido'

@login_required
def index(request):
    page = int(request.GET.get('page', 1))
    name = request.GET.get('name', None)
    if name is None:
        return render(request, 'patient/list.html')
    patient_list = Patient.objects.filter(name__contains=name)
    paginator = Paginator(patient_list, 25)

    try:
        patients = paginator.page(page)
    except PageNotAnInteger:
        patients = paginator.page(1)
    except EmptyPage:
        patients = paginator.page(paginator.num_pages)
    page_range = range(1, patients.paginator.num_pages + 1)
    return render(request, 'patient/list.html', {
        'patients': patients, 'page_range': page_range, 'name': name})

@login_required
def create(request):
    title = 'Novo paciente'
    response_args = {
        'title': title,
        'form': PatientForm(),
        'number': get_registry_number(),
    }
    if request.method == 'POST':
        form = PatientForm(request.POST)
        if form.is_valid():
            patient = form.save()
            response_args['number'] = response_args['number'] + 1
            response_args.update({
                'flash': create_flash('green', 'Paciente criado com sucesso!')
            })
        else:
            response_args['form'] = form
            response_args.update({
                'flash': create_flash('red', get_error_msg(form))
            })

    return render(
        request, 'patient/view.html', response_args)

@login_required
def edit(request, patient_id):
    patient = get_object_or_404(Patient, pk=patient_id)
    form = PatientForm(instance=patient)
    response_args = {
        'title': 'Editar Paciente',
        'number': patient.id,
        'patient': patient,
        'form': form
    }
    if request.method == 'GET':
        return render(
            request, 'patient/view.html', response_args)
    else:
        form = PatientForm(request.POST, instance=patient)
        response_args['form'] = form
        if form.is_valid():
            patient.save()
            response_args.update({
                'flash': create_flash('green', 'Paciente editado com sucesso!')
            })
        else:
            response_args.update({
                'flash': create_flash('red', get_error_msg(form))
            })
        return redirect('patient:list')

@login_required
def print_patient(request, patient_id):
    patient = get_object_or_404(Patient, pk=patient_id)
    return render(
            request, 'patient/print.html',
            {
                'title': 'Paciente',
                'patient': patient,
                'time': datetime.now().strftime('%d/%m/%Y'),
                'CHARACTER_CHOICES': CHARACTER_CHOICES,
                'REFERAL_PLACES': REFERAL_PLACES,
                'patient_age': patient.get_age()
            })

sdh/views.py
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    return redirect('patient:list')

patient/templates/patient/list.html
{% extends 'base_generic.html' %}

{% block content %}

<h2>Pacientes</h2>


<div class="row">
    <form class="col s12" action="{% url 'patient:list' %}">
      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">search</i>
          <input name="name" id="icon_prefix" type="text" value="{{name}}">
          <label for="name">Nome do paciente</label>
        </div>
      </div>
      <button type="submit" class="waves-effect waves-light btn">pesquisar</button>
    </form>
  </div>

{% if patients %}

<ul class="collapsible" data-collapsible="accordion">
    {% for patient in patients %}
        <li>
            <div class="collapsible-header valign-wrapper">
                    {{ patient.name|upper }}
            </div>
            <div class="collapsible-body">
                <div class="row">
                    <div class="col s4">
                        {% if patient.mother_name %}
                            <p><b>Nome da mãe: </b> {{ patient.mother_name }}</p>
                        {% endif %}
                        <p><b>Endereço: </b> {{ patient.address }}</p>
                        <p><b>Telefone: </b> {{ patient.phone }}</p>
                        <p><b>Aniversário: </b> {{ patient.birthdate|date:"d/m/Y" }}</p>
                    </div>
                    {% if patient.notes %}
                        <div class="col s4">
                            <p><b>Observações: </b> {{ patient.notes }}</p>
                        </div>
                    {% endif %}
                    <div class="col s4">
                            <p class="valign-wrapper"><b>Histórico familiar: </b> {% if patient.prostate_history %} <i class="material-icons red-text">check</i> {% else %} <i class="material-icons green-text">clear</i> {% endif %}</p>
                            <p class="valign-wrapper"><b>Problemas para urinar: </b> {% if patient.trouble_urinating %} <i class="material-icons red-text">check</i> {% else %} <i class="material-icons green-text">clear</i> {% endif %}</p>
                            <p class="valign-wrapper"><b>Nódulo suspeito: </b> {% if patient.suspicious_nodule %} <i class="material-icons red-text">check</i> {% else %} <i class="material-icons green-text">clear</i> {% endif %}</p>
                            <p class="valign-wrapper"><b>Exame PSA positivo: </b> {% if patient.psa_positive %} <i class="material-icons red-text">check</i> {% else %} <i class="material-icons green-text">clear</i> {% endif %}</p>
                    </div>
                </div>
                <a href="/patients/{{patient.id}}" class="waves-effect waves-light orange btn"><i class="material-icons white-text left">edit</i>Editar</a>
                <a href="/patients/{{patient.id}}/print" class="waves-effect waves-light orange btn"><i class="material-icons white-text left">print</i>Imprimir</a>
            </div>
        </li>
  {% endfor %}
</ul>

<ul class="pagination center">
    <span class="step-links">
        <li
            {% if patients.has_previous %}
                class="waves-effect"><a href="?page={{patients.previous_page_number}}&name={{name}}"><i class="material-icons">chevron_left</i></a>
            {% else %}
                class="disabled"><a><i class="material-icons">chevron_left</i></a>
            {% endif %}
        </li>
        {% for number in page_range %}
            <li {% if number == patients.number %} class="active orange" {% else %} class="waves-effect" {% endif %} ><a href="?page={{number}}&name={{name}}">{{number}}</a></li>
        {% endfor %}
        <li
            {% if patients.has_next %}
                class="waves-effect"><a href="?page={{patients.next_page_number}}&name={{name}}"><i class="material-icons">chevron_right</i></a>
            {% else %}
                class="disabled"><a><i class="material-icons">chevron_right</i></a>
            {% endif %}
        </li
    </span>
</ul>

{% else %}

    {% if name %}
        <p> <b> Nenhum paciente com nome contendo "{{ name }}" </b></p>
    {% else %}
        <p> <b> Pesquise por pacientes </b></p>
    {% endif %}

{% endif %}

<div class="fixed-action-btn">
    <a class="btn-floating btn-large orange" href="{% url 'patient:new' %}">
        <i class="large material-icons">add</i>
    </a>
</div>

{% endblock %}

patient/templates/patient/print.html
{% extends 'base_generic.html'%}
{% block styles %}
    <link href="/static/css/style.css" type="text/css" rel="stylesheet"/>
{% endblock %}
{% block content %}
<br>
<ul>
    <li>
        <div class="row valign-wrapper">
            <div class="col m6 form-label-md" >
                <b> CADASTRO NÚMERO: </b> {{patient.id}}
            </div>
            <div class="col m6 form-label-sm " >
                <b> Data: </b> {{ time }}
            </div>
        </div>
    </li>
    <li>
        <div class="row">
            <div class="col m6 form-label-sm" >
                <b> Nome: </b> {{patient.name|upper}}
            </div>
        </div>
    </li>
    {% if patient.mother_name %}
        <li>
            <div class="row">
                <div class="col m6 form-label-sm" >
                    <b> Nome da mãe: </b> {{patient.mother_name|upper}}
                </div>
            </div>
        </li>
    {% endif %}
    <li>
        <div class="row">
            <div class="col form-label-sm" >
                <b> Endereço: </b> {{patient.address|upper}}
            </div>
        </div>
    </li>
    <li>
        <div class="row">
            <div class="col form-label-sm" >
                <b> Telefone: </b> {{patient.phone}}
            </div>
        </div>
    </li>
    <li>
        <div class="row">
            <div class="col m4 form-label-sm" >
                <b> Data de nascimento: </b> {{patient.birthdate|date:"d/m/Y"}}
            </div>
            <div class="col m4 form-label-sm" >
                <b> Idade: </b> {{patient_age}}
            </div>
        </div>
    </li>
    <li>
        <div class="row">
            <div class="col m3 form-label-sm" >
                <b> Histórico familiar: </b> {% if patient.prostate_history %} SIM {% else %} NÃO {% endif %}
            </div>
            <div class="col m3 form-label-sm" >
                <b> Problemas para urinar: </b> {% if patient.trouble_urinating %} SIM {% else %} NÃO {% endif %}
            </div>
            <div class="col m3 form-label-sm" >
                <b> Nódulo suspeito: </b> {% if patient.suspicious_nodule %} SIM {% else %} NÃO {% endif %}
            </div>
            <div class="col m3 form-label-sm" >
                <b>Exame PSA positivo: </b> {% if patient.psa_positive %} SIM {% else %} NÃO {% endif %}
            </div>
        </div>
    </li>
    {% if patient.notes %}
        <li>
            <div class="row">
                <div class="col form-label-sm" >
                    <b> Observações: </b> {{patient.notes}}
                </div>
            </div>
            <br><br><br>
        </li>
    {% endif %}
    {% if patient.has_referral %}
        <li>
            <div class="row">
                <div class="col form-label-sm" style="text-align: justify;">
                    <b> O PACIENTE PARTICIPOU DA SEMANA DA SAÚDE DA SECRETARIA DE SAÚDE DO ESTADO DO RIO DE JANEIRO (AÇÃO DO NOVEMBRO AZUL) E FOI ENCAMINHADO PARA O SEGUINTE LOCAL PARA MARCAÇÃO DE CONSULTA: </b>
                </div>
            </div>
            <div class="row">
                <div class="col m6 form-label-sm" >
                    <b> Caráter: </b> {% if patient.referral_character == 0 %} {{ CHARACTER_CHOICES.O }} {% else %} {{CHARACTER_CHOICES.1}} {% endif %}
                </div>
                <div class="col m6 form-label-sm">
                    <b> Local: </b> {% if patient.referral_character == 0 %} {{ REFERAL_PLACES.O }} {% elif patient.referral_character == 1 %} {{REFERAL_PLACES.1}} {% else %} {{REFERAL_PLACES.2}}: {{patient.other_referral_place}} {% endif %}
                </div>
            </div>
        </li>
    {% endif %}
    <li class="center">
        <br><br><br>
        <p>Atenciosamente, Data: {{time}}</p>
        <br><br>
        <hr>
    </li>
</ul>
{% endblock %}

patient/templates/patient/view.html
{% extends 'base_generic.html'%}
{% block content %}

<h4>Cadastro número {{number}}</h4>

{% if patient %}
    <form action="{% url 'patient:edit' patient.id %}" method="post" novalidate>
{% else %}
    <form action="{% url 'patient:new' %}" method="post" novalidate>
{% endif %}
    {% csrf_token %}
    <div class="row">
        {% for field in form %}
            <div class="input-field col s6">
            {{ field }}
            <label for="{{field.name}}">{{field.label}}</label>
            </div>
        {% endfor %}
    </div>

    <button class="orange btn waves-effect waves-light btn-large" type="submit" name="action">Salvar
        <i class="material-icons right">send</i>
    </button>
</form>

{% endblock %}

{% block scripts %}
<script src="/static/js/jquery.mask.min.js" ></script>
<script type="text/javascript">
    if (window.history.replaceState) {
      window.history.replaceState( null, null, window.location.href );
    }
    $(document).ready(function() {
        $('select').material_select();
        toggleOther();
        toggleReferral();
        $('#id_birthdate').mask("00/00/0000", {placeholder: "__/__/____"});
    });

    $('form').submit(function() {
      $(this).find("button[type='submit']").prop('disabled',true);
    });

    $("#id_referral_place").on('change', function() {
        toggleOther();
    })

    $('#id_has_referral').on('change', function() {
        toggleReferral();
    });

    function toggleReferral() {
        var value = $('#id_has_referral').val();
        if (value === '2') {
            $('#id_referral_character').parent().parent().show();
            $('#id_referral_place').parent().parent().show();
        } else {
            $('#id_other_referral_place').val("");
            $('#id_referral_character').val("");
            $('#id_referral_place').val("");
            $('#id_referral_character').parent().parent().hide();
            $('#id_referral_place').parent().parent().hide();
        }
        toggleOther();
    }

    function toggleOther() {
        if ($("#id_referral_place").val() === '2') {
            $("#id_other_referral_place").parent().show();
        } else {
            $("#id_other_referral_place").parent().hide();
        }
    }
</script>
{% endblock %}

templates/base_generic.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Semana da Saúde</title>

  <!-- CSS  -->
  <link href="/static/css/material_icons.css" type="text/css" rel="stylesheet"/>
  <link href="/static/css/materialize.min.css" type="text/css" rel="stylesheet"/>
</head>
<body>
  <nav class="blue darken-4" role="navigation">
      <div class="container nav-wrapper">
        <a href="#" data-activates="mobile-menu" class="button-collapse"><i class="material-icons">menu</i></a>
        <a href="{% url 'patient:list' %}" class="brand-logo center"><img src="/static/img/logo.png"></a>
      {% if user.is_authenticated %}
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><a href="{% url 'patient:list' %}">Início</a></li>
          {% if request.get_full_path == '/patients/new' %}
            <li><a href="{% url 'patient:list' %}">Voltar</a></li>
          {% else %}
            <li><a href="{% url 'patient:new' %}">Cadastrar</a></li>
          {% endif %}
        </ul>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="{% url 'logout' %}">Sair</a></li>
        </ul>
        <ul id="mobile-menu" class="side-nav">
          <li><a href="{% url 'patient:list' %}">Início</a></li>
          {% if request.get_full_path == '/patients/new' %}
            <li><a href="{% url 'patient:list' %}">Voltar</a></li>
          {% else %}
            <li><a href="{% url 'patient:new' %}">Cadastrar</a></li>
          {% endif %}
          <li><a href="{% url 'logout' %}">Sair</a></li>
        </ul>
    {% endif %}
      </div>
    </div>
  </nav>


  <div class="container">
    {% block content %} {% endblock %}
  </div>

  <script src="/static/js/jquery-3.2.1.min.js" ></script>
  <script src="/static/js/materialize.min.js" ></script>
  {% block scripts %} {% endblock %}

  <script type="text/javascript">
    {% if flash is not None %}
        $(function() {
          var msg = $.parseHTML('<div>{{flash.message}}</div>')
          Materialize.toast($(msg) , 4000, '{{flash.color}}')
        })
    {% endif %}
    $(".button-collapse").sideNav();
  </script>

  </body>
</html>

templates/index.html
{% extends 'base_generic.html' %}
{% block content %}
  <div class="row center">
    <div class="col m12">
      <a href="{% url 'patient:list' %}" class="black-text">
        <div class="card-panel">
          <br><br><br><br>
          <h2 class="center-align">Saúde do homem</h2>
          <br><br><br><br>
      </div>
      </a>
    </div>
  </div>
{% endblock %}

templates/login.html
{% extends 'base_generic.html' %}

{% block content %}
  <h2>Login</h2>
  <form  method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="row margin">
      <div class="input-field col s12">
        {{ field }}
        <label for="{{field.name}}">{{field.label}}</label>
      </div>
    </div>
    {% endfor %}
    <button class="btn orange" type="submit">Login</button>
  </form>
  </div>

{% endblock %}